server:
    port: 8080

spring:
    application:
        name: bankcards
    datasource:
        url: jdbc:postgresql://localhost:5432/bankcards_db
        username: bankcards_user
        password: bankcards_password
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                globally_quoted_identifiers: true
        open-in-view: false
    liquibase:
        change-log: classpath:db/migration/changelog-main.yml

springdoc:
    swagger-ui:
        url: /docs/specification.yml

logging:
    level:
      root: INFO
      com.example.bankcards: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

jwt:
    secret: 54ed12915ff41335900fbaa1d33ce53e28e359cc790f2eb58fd1e619eaa1e11c5ad429ea54e382ea15fb8db219f6e0f60b9f7d14b12fd1910157929abaeb8674
    expiration: 86400000 # ms (24 hours)

crypto:
    secret: 14be81435b18043d5a6619a4fcedfca7
