#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
    port: 8080

spring:
    application:
        name: bankcards
    datasource:
        url: jdbc:postgresql://localhost:5432/bankcards_db
        username: bankcards_user
        password: bankcards_password
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                globally_quoted_identifiers: true
        open-in-view: false
    liquibase:
        change-log: classpath:db/migration/changelog-main.yml

logging:
    level:
      root: INFO
      com.example.bankcards: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
